#!/usr/bin/env ruby

class SmallestMulitpleSolver
  class << self
    MIN = 10000000
    MAX = 999999999

    def solution
      puts solve
    end

    private

    def is_lowest_multiple?(num)
      divisors.each do |n|
        if is_divisable?(num,n)
          return true if n == 20
        else
          return false
        end
      end
    end

    def is_divisable?(num, n)
      num.divmod(n)[1] == 0
    end

    def solve
      candidates.step(20) { |n| return n if is_lowest_multiple? n }
    end

    def candidates
      (MIN..MAX)
    end

    def divisors
      (1..20)
    end
  end
end

SmallestMulitpleSolver.solution
